version: "3"
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code

  postgres:
    image: "postgres:alpine"
    env_file:
      - configs/env_configs/.env-postgres
    ports:
      - "15432:5432"
    volumes:
      - /home/maria/podtgres_mini_jobninja:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - configs/env_configs/.env-postgres
    ports:
      - "16543:80"
    depends_on:
      - postgres
